pipeline {
    agent any
    stages {
        stage("test"){
            steps{
                sh "echo Hello >> file1"
                sh "echo hi >> file2"
                sh "echo greetings >> file3"
            }
        }
    }
}
